### PR TITLE
fix: http -> https

### PR DESCRIPTION
**Pull request by Hongbo-Miao**
Switch to https, otherwise will get this error:

image

### CODE REVIEW

**Comment by Hongbo-Miao** [comment]
@typicode done.

**Comment by typicode** [comment]
Awesome thanks!

**Comment by Hongbo-Miao** [comment]
you are welcome!

**Comment by Hongbo-Miao** [comment]
@typicode u need update a little style

image

**Comment by typicode** [comment]
should be good, thanks for the heads up :+1:

**Pull request merged**
